name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23lisUEIGov9sZCODk"
GITHUB_OWNER = "jeoitim"
GITHUB_REPO = "navsphere-jeoitim"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://jeoitim.cc.cd/api/auth"
NEXT_PUBLIC_API_URL="https://jeoitim.cc.cd/"

